<?php
//  ------------------------------------------------------------------------ //
// 本模組由 kimozi 製作
// 製作日期：2009-07-14
// $Id:$
// ------------------------------------------------------------------------- //

//define ( "_BACK_MODULES_PAGE", "Back to module home page"); 
define ( "_FUNCTION_MESSAGE_SORRY", "I am sorry, your appointment failed!! <br> may be at the same time, it was faster than hand-Oh!! <br> system will automatically return to home page!"); 

// Paging object language used in 
define ( "_BP_BACK_PAGE", "Previous"); 
define ( "_BP_NEXT_PAGE", "Next"); 
define ( "_BP_FIRST_PAGE", "First"); 
define ( "_BP_LAST_PAGE", "Last"); 
define ( "_BP_GO_BACK_PAGE", "before %s pages"); 
define ( "_BP_GO_NEXT_PAGE", "after the %s page"); 
define ( "_BP_TOOLBAR", "Total %s page %s is currently the first page:"); 
define ( "_BP_DEL_CHK", "sure you want to delete this information?"); 
define ( "_BP_FUNCTION", "function"); 
define ( "_BP_EDIT", "Edit"); 
define ( "_BP_DEL", "delete"); 
define ( "_BP_ADD", "additional information");
define ( "_MA_INPUT_FORM", "Input Form"); 
define ( "_MA_SAVE", "Save"); 
define ( "_MA_ADMIN_BOOKING_SUBMIT", "submit query"); 
define ( "_MD_INPUT_VALID ","%s field checks "); 
define ( "_MD_INPUT_VALIDATOR", "Please enter %s"); 
define ( "_MD_INPUT_VALIDATOR_ERROR", "%s incorrect"); 
define ( "_MD_INPUT_VALIDATOR_CHK", "at least %s characters, a maximum of %s characters"); 
define ( "_MD_INPUT_VALIDATOR_MIN", "at least %s characters"); 
define ( "_MD_INPUT_VALIDATOR_MAX", "up to %s characters"); 
define ( "_MD_INPUT_VALIDATOR_EQUAL", "limit %s characters"); 
define ( "_MD_INPUT_VALIDATOR_NEED", "can not be blank"); 
define ( "_MD_INPUT_VALIDATOR_RANGE", "scope: %s ~%s"); 
define ( "_MD_INPUT_VALIDATOR_RANGE_MIN", "Minimum: %s"); 
define ( "_MD_INPUT_VALIDATOR_RANGE_MAX", "Maximum: %s"); 
//define ( "_MI_KIMOZIJACANA_ADMENU1", "Online booking at a Glance"); 
//define ( "_MI_KIMOZIJACANA_ADMENU2", "★ preset time slots / number of ★"); 
//define ( "_MI_KIMOZIJACANA_ADMENU3", "set off Garden Day"); 
//define ( "_MI_KIMOZIJACANA_ADMENU4", "Prohibition of appointment (time)"); 

define ( "_MA_KIMOZIJACANA_ORDER_SN", "booking a single ID"); 
define ( "_MA_KIMOZIJACANA_O_DATE", "record date"); 
define ( "_MA_KIMOZIJACANA_O_BOOKING_DATE", "Booking Date"); 
define ( "_MA_KIMOZIJACANA_O_PERIOD", "scheduled time"); 
define ( "_MA_KIMOZIJACANA_O_BOOKING_NUM", "predetermined number"); 
define ( "_MA_KIMOZIJACANA_O_ORGANIZATION", "reservation unit"); 
define ( "_MA_KIMOZIJACANA_O_CONTACT", "contact person"); 
define ( "_MA_KIMOZIJACANA_O_TEL", "phone"); 
define ( "_MA_KIMOZIJACANA_O_FAX", "fax"); 
define ( "_MA_KIMOZIJACANA_O_CELLPHONE", "mobile phone"); 
define ( "_MA_KIMOZIJACANA_O_EMAIL", "Email"); 
define ( "_MA_KIMOZIJACANA_O_MARK", "Other matters"); 
define ( "_MA_KIMOZIJACANA_O_OK", "accept the appointment"); 

define ( "_MA_ORGANIZATION_TITLE", "Jacana Restoration Zone"); 
define ( "_MA_ORGANIZATION_ADMIN", "administrator"); 
define ( "_MA_ORGANIZATION_DIV_TITLE", "Blackout Date/time"); 
define ( "_MA_KIMOZIJACANA_O_OK_NO", "No"); 
define ( "_MA_KIMOZIJACANA_O_OK_YES", "Yes"); 
define ( "_MA_SHOW_ADMIN_ATTENTION_WORKER", "Advanced Info"); 
define ( "_MA_ADMIN_BOOKING_ATTENTION", " 
Please set up the first time: <p> ★ default time slots / number. </ p> 
<p> ★ preset time slots / number of people removed 『』 did not function, to avoid an error. In future, if 』『 editing slots / number of appointments have been generated by a single, will correspond to the new settings. </ p> 
<p> ★ administrator wants an appointment that has an open day 』『 will be given an administrator through the process to add the proposed appointment; instead of opening date, only the use of new 』『 function. </ p> 
<p> ★ Use editing feature to modify a single reservation, please refer to the day limit, the system does not check for it! But gives the administrator the power to change it! </ p> 
");

?>